import { Router } from "express";
const router = Router();

import roleRouter from "./role.routes";
import staffRouter from "./staff.routes";
import authRouter from "./auth.routes";
import hostelRouter from "./hostel.routes";
import userRouter from "./user.routes";
import dashboardRouter from "./dashboard.routes";
import messMenuRouter from "./mess.routes";
import complainCategoryRouter from "./complainCategory.routes";
import complainSubCategoryRouter from "./complainSubCategory.routes";
import complaintRouter from "./complaint.routes";
import leaveCategoryRouter from "./leaveCategory.routes";
import studentLeaveRouter from "./studentLeave.routes";
import pageRoutesRouter from "./pageRoutes.routes";
import userReportRouter from "./userReport.routes";
import maintenanceReportRouter from "./maintenanceReport.routes";
import messReportRouter from "./messReport.routes";
import leaveReportRouter from "./leaveReport.routes";
import permissionRouter from "./permission.routes";
import bulkUploadRoutes from "./bulkUpload.routes";
import courseRouters from "./course.routes";
import universityRouters from "./university.routes";
import amenitieRouters from "./amenitie.routes";
import foodWastageRouters from "./foodWastage.routes";
import foodWastageReportRouters from "./foodWastageReport.routes";
import templateRouters from "./template.routes";
import noticeRouter from "./notice.routes";

router.use("/role", roleRouter);
router.use("/staff", staffRouter);
router.use("/auth", authRouter);
router.use("/hostel", hostelRouter);
router.use("/user", userRouter);
router.use("/dashboard", dashboardRouter);
router.use("/mess", messMenuRouter);
router.use("/complaint-category", complainCategoryRouter);
router.use("/complaint-sub-category", complainSubCategoryRouter);
router.use("/complaint", complaintRouter);
router.use("/leave-category", leaveCategoryRouter);
router.use("/leave-management", studentLeaveRouter);
router.use("/page-routes", pageRoutesRouter);
router.use("/user-report", userReportRouter);
router.use("/maintenance-report", maintenanceReportRouter);
router.use("/mess-report", messReportRouter);
router.use("/leave-report", leaveReportRouter);
router.use("/permission", permissionRouter);
router.use("/bulk-upload", bulkUploadRoutes);
router.use("/course", courseRouters);
router.use("/university", universityRouters);
router.use("/amenitie", amenitieRouters);
router.use("/food-wastage", foodWastageRouters);
router.use("/food-wastage-report", foodWastageReportRouters);
router.use("/template", templateRouters);
router.use("/notice", noticeRouter);

export default router;
