import Joi from "joi";

const metaSchema = Joi.object({
  order: Joi.number().integer(),
  visibleTo: Joi.array().items(Joi.string()),
  priority: Joi.string(),
  defaultTemplateId: Joi.string(),
});

// Schema for existing subcategories (used in updates/storage)
const subcategorySchema = Joi.object({
  title: Joi.string().max(150).required(),
  slug: Joi.string().max(60).required(),
  description: Joi.string().max(500).allow(null, ""),
  meta: metaSchema.optional(),
  isActive: Joi.boolean().default(true),
  createdAt: Joi.date().optional(),
  updatedAt: Joi.date().optional(),
  _id: Joi.any().optional(), // allow _id in generic schema
});

// Schema for creating a NEW subcategory (slug generated by backend)
// Schema for creating a NEW subcategory (slug generated by backend)
export const createSubcategorySchema = Joi.object({
  title: Joi.string().max(150).trim().required(),
  slug: Joi.string().forbidden(),
  description: Joi.string().max(500).allow(null, ""),
  meta: metaSchema.optional(),
  isActive: Joi.boolean().default(true),
});

export const createGlobalTemplateSchema = Joi.object({
  // _id is optional - if provided, it's an UPDATE operation
  _id: Joi.string()
    .pattern(/^[0-9a-fA-F]{24}$/)
    .optional(),

  // Title required
  title: Joi.string().max(150).required(),

  // Slug optional in input (server generates it from title), but if provided must match pattern
  slug: Joi.string()
    .max(60)
    .pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)
    .optional(),

  description: Joi.string().max(1000).allow(null, ""),
  scope: Joi.string().valid("global", "hostel").default("global"),
  hostelId: Joi.when("scope", {
    is: "hostel",
    then: Joi.string().required().allow(null),
    otherwise: Joi.string().allow(null),
  }),
  // Subcategories not used in main create flow as per recent requirements, but allowed validation-wise
  subcategories: Joi.array().items(subcategorySchema).default([]),
  isActive: Joi.boolean().default(true),
  isDeleted: Joi.boolean().default(false),
  version: Joi.number().optional(),
});

export const updateGlobalTemplateSchema = Joi.object({
  title: Joi.string().max(150),
  description: Joi.string().max(1000).allow(null, ""),
  subcategories: Joi.array().items(subcategorySchema),
  isActive: Joi.boolean(),
  isDeleted: Joi.boolean(),
  scope: Joi.string().valid("global", "hostel"),
  hostelId: Joi.string().allow(null),
});
